export const COLORS: Record<string, string> = {
  background: 'bg-background',
  foreground: 'bg-foreground',
  card: 'bg-card',
  'card-foreground': 'bg-card-foreground',
  popover: 'bg-popover',
  'popover-foreground': 'bg-popover-foreground',
  primary: 'bg-primary',
  'primary-foreground': 'bg-primary-foreground',
  secondary: 'bg-secondary',
  'secondary-foreground': 'bg-secondary-foreground',
  muted: 'bg-muted',
  'muted-foreground': 'bg-muted-foreground',
  accent: 'bg-accent',
  'accent-foreground': 'bg-accent-foreground',
  success: 'bg-success',
  'success-foreground': 'bg-success-foreground',
  warning: 'bg-warning',
  'warning-foreground': 'bg-warning-foreground',
  border: 'bg-border',
  input: 'bg-input',
  ring: 'bg-ring',
};
